version: "3.9"

services:
  db:
    tty: true
    restart: unless-stopped
    image: postgres:15.3-alpine3.18
    container_name: postgres-${PROJECT_SUFFIX:-the_remember}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - db_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      -  env/.env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT:-5432}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

  backend:
    tty: true
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    image: daniinxorchenabo/the_remember_app_backend:latest
    container_name: backend-${PROJECT_SUFFIX:-the_remember}
    build:
      context: ./the_remember

    command: >
      bash -c "
      python -m alembic --config ./the_remember/src/repo/migration/_alembic.ini  upgrade head && uvicorn main:app --port ${TR_BACKEND_PORT} --host 0.0.0.0 --workers ${TR_BACKEND_APP_WORKERS_COUNT} --log-level debug      
      "

    links:
      - "db:database"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "${TR_BACKEND_PORT}:${TR_BACKEND_PORT}"
    env_file:
      -  env/.env
    volumes:
      - type: bind
        source: .
        target: /projects/the_remember_backend
    networks:
      - db_network
      - production_network

  db_backup:
    tty: true
    restart: unless-stopped
    image: prodrigestivill/postgres-backup-local
    container_name: postgres-backup-${PROJECT_SUFFIX:-the_remember}
    volumes:
      - db_backup_volume:/var/lib/postgresql/the_remember_data_backup

    networks:
      - db_network
    links:
      - db:postgres-${PROJECT_SUFFIX:-the_remember}
      - db:database
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - env/.env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_EXTRA_OPTS=${POSTGRES_EXTRA_OPTS}
      - SCHEDULE=${POSTGRES_BACKUP_SCHEDULE}
      - BACKUP_DIR=/var/lib/postgresql/the_remember_data_backup
      - BACKUP_KEEP_DAYS=${POSTGRES_BACKUP_KEEP_DAYS}
      - BACKUP_KEEP_WEEKS=${POSTGRES_BACKUP_KEEP_WEEKS}
      - BACKUP_KEEP_MONTHS=${POSTGRES_BACKUP_KEEP_MONTHS}
      - HEALTHCHECK_PORT=${POSTGRES_BACKUP_HEALTHCHECK_PORT}




volumes:
  db_volume:
    name: db-data-${POSTGRES_VOLUME_NAME:-postgres}-${PROJECT_SUFFIX:-the_remember}
    external: false
  db_backup_volume:
    name: db-data-backups-${POSTGRES_VOLUME_NAME:-postgres}-${PROJECT_SUFFIX:-the_remember}
    external: false


networks:
  db_network:
    name: db-network-${POSTGRES_NETWORK_NAME:-postgres}-${PROJECT_SUFFIX:-the_remember}
#    external: true
#    internal: false

  production_network:
    name: external-network-${PROJECT_SUFFIX:-the_remember}
#    external: false
#    internal: false
