version: "3.9"

services:
  db:
    tty: true
    restart: unless-stopped
    image: postgres:15.3-alpine3.18
    container_name: postgres-${PROJECT_SUFFIX:-the_remember}
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - db_network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      -  env/.env
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT:-5432}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

  backend:
    depends_on:
      db:
        condition: service_healthy
    image: daniinxorchenabo/the_remember_app_backend:latest
    build:
      context: ./the_remember

    command:      >
      bash -c "
      python -m alembic --config .\the_remember\src\repo\migration/_alembic.ini  upgrade head 
       && uvicorn main:app --port ${TR_BACKEND_PORT} --host 0.0.0.0 --workers ${TR_BACKEND_APP_WORKERS_COUNT} --log-level debug      "

    links:
      - "db:database"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "${TR_BACKEND_PORT}:${TR_BACKEND_PORT}"
    env_file:
      -  env/.env
    volumes:
      - type: bind
        source: .
        target: /projects/the_remember_backend
    networks:
      - db_network
      - production_network




volumes:
  db_volume:
    name: db-data-${POSTGRES_VOLUME_NAME:-postgres}-${PROJECT_SUFFIX:-the_remember}
    external: false

networks:
  db_network:
    name: db-network-${POSTGRES_NETWORK_NAME:-postgres}-${PROJECT_SUFFIX:-the_remember}
#    external: true
#    internal: false

  production_network:
    name: external-network-${PROJECT_SUFFIX:-the_remember}
#    external: false
#    internal: false
