"""add sentence table

Revision ID: e49d6e8364c5
Revises: 62e034531d8f
Create Date: 2023-08-14 15:20:21.213652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49d6e8364c5'
down_revision = '62e034531d8f'
branch_labels = None
depends_on = None


def upgrade():
    # TODO: check it!
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('sentence', sa.String(), nullable=False),
    sa.Column('translate', sa.String(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['term_id'], ['term.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('module', sa.Column('description', sa.String(), nullable=True))
    op.add_column('term', sa.Column('transcription', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # TODO: check it!
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('term', 'transcription')
    op.drop_column('module', 'description')
    op.drop_table('sentence')
    # ### end Alembic commands ###
