"""add learn metrics yet

Revision ID: 7ddbededca1f
Revises: 5ae055ee5c27
Create Date: 2023-08-28 14:21:24.702538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddbededca1f'
down_revision = '5ae055ee5c27'
branch_labels = None
depends_on = None


def upgrade():
    # TODO: check it!
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalize_module', sa.Column('is_learnt', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # TODO: check it!
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalize_module', 'is_learnt')
    # ### end Alembic commands ###
