"""add persoanalized created_at and updated_at fields

Revision ID: 62e034531d8f
Revises: 473abe82d3fc
Create Date: 2023-08-12 22:27:38.779089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e034531d8f'
down_revision = '473abe82d3fc'
branch_labels = None
depends_on = None


def upgrade():
    # TODO: check it!
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personalize_module', sa.Column('personal_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('personalize_module', sa.Column('personal_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('personalize_term', sa.Column('personal_created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('personalize_term', sa.Column('personal_updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # TODO: check it!
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personalize_term', 'personal_updated_at')
    op.drop_column('personalize_term', 'personal_created_at')
    op.drop_column('personalize_module', 'personal_updated_at')
    op.drop_column('personalize_module', 'personal_created_at')
    # ### end Alembic commands ###
